name: Terraform Compliance Check
on:
  push:
  workflow_dispatch:

jobs:
  checkov-job:
    runs-on: ubuntu-latest
    name: checkov-action
    steps:
      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          framework: terraform
          check: CKV_AWS_130
          quiet: false
          soft_fail: false
          log_level: DEBUG
